language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8
          dist: xenial
          sudo: true

addons:
  apt:
    packages:
    - python-dev
    - libxml2-dev
    - libxslt1-dev

install:
  - "pip install -r development.txt"
  - "pip install -r requirements.txt"

script: nosetests -v --with-coverage --cover-package=jnpr.junos --cover-inclusive -a unit

after_success:
  coveralls

notifications:
  email: false
